version: '2'
services:
   healthcheck_mongo:
      image: mongo
      container_name: healthcheck_mongo
      hostname: healthcheck_mongo
      ports:
        - 27017
      volumes:
      - /home/myroot/docker.shell/healthcheck/data:/data/db      
      command: mongod --directoryperdb  
      
   healthcheck:
      depends_on:
        - healthcheck_mongo
      image: jokyip/healthcheck
      container_name: healthcheck
      hostname: healthcheck
      volumes:
       - /home/myroot/docker.shell/healthcheck/conf/server.coffee:/usr/src/app/config/env/production.coffee
       - /home/myroot/docker.shell/healthcheck/conf/client.coffee:/usr/src/app/www/js/env.coffee
       - /etc/ssl/certs:/etc/ssl/certs       
       - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
   